sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
env:
  global:
    - RUST_BACKTRACE=1
script:
  - cargo build
  - cargo test
  - cargo install --path .
  - cargo build-deps